x-common-variables: &common-variables
  POSTGRES_DB: stubasos
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin

services:
  reverse-proxy:
    image: nginx:latest
    ports:
      - 80:3000 # frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - postgres
    links:
      - frontend
      - postgres

  frontend:
    build: ./frontend/
    image: stuba-asos-frontend:latest
    expose:
      - "3000"

  backend:
    build: ./backend/
    image: stuba-asos-backend:latest
    environment: 
      AUTH_JWT_ALG: HS256
      AUTH_JWT_SECRET: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      DB_URL: postgresql://admin:admin@postgres:5432/stubasos
    expose:
      - "8502"
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: postgres:17-bookworm
    environment: *common-variables
    expose:
      - "5432"
    volumes:
      - ./initdb/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres:/var/lib/postgresql/data

  postgres-test:
    image: postgres:17-bookworm
    environment: 
      POSTGRES_DB: test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    expose:
      - "5432"

volumes:
  postgres:
