x-common-variables: &common-variables
  POSTGRES_DB: stubasos
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin

services:
  reverse-proxy:
    image: nginx:latest
    container_name: stuba-asos-proxy
    ports:
      - 80:8501 # frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - postgres
    links:
      - frontend
      - postgres

  frontend:
    build: ./frontend/
    image: stuba-asos-frontend:latest
    container_name: stuba-asos-frontend
    expose:
      - "8501"

  backend:
    build: ./backend/
    image: stuba-asos-backend:latest
    container_name: stuba-asos-backend
    environment: 
      JWT_ALG: HS256
      JWT_SECRET: 
      DATABASE_URL: postgresql://admin:admin@postgres:5432/stubasos
    expose:
      - "8502"
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: postgres:17-bookworm
    container_name: postgres
    environment: *common-variables
    ports:
      - "5434:5432"
    volumes:
      - ./initdb/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
