name: Dev Deploy to Remote Server http://46.101.254.37/

permissions:
  pull-requests: read
  deployments: read
  contents: read

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  push:
    branches:
      - main

jobs:
  deploy_dev:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.DEV_SSH_KEY}}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 46.101.254.37 >> ~/.ssh/known_hosts
          echo pwd

      - name: Deploy and run Docker Compose
        env:
          BRANCH: ${{ github.head_ref }}
        run: |
          ssh -i /home/runner/.ssh/id_ed25519 -o StrictHostKeyChecking=no dev@46.101.254.37 << 'EOF'
            set -e
            cd /home/dev/stuba-asos
            echo "Stopping and removing the containers"
            docker compose down
            echo
            echo "Pulling the latest changes from the repository"
            echo "${{ env.BRANCH }}"
            git fetch
            git checkout "${{ env.BRANCH }}"
            git pull
            echo
            echo "Building and deploying the project"
            docker compose -f docker-compose-dev.yaml up --build -d
          EOF
