name: Dev Deploy to Remote Server http://46.101.254.37/

permissions:
  pull-requests: read
  deployments: read
  contents: read

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  push:
    branches:
      - main

jobs:
  deploy_dev:
    runs-on: ubuntu-latest

    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.1.0
      with:
            host: ${{ secrets.HOST }}
            key: ${{ secrets.PASSWORD }}
            username: ${{ secrets.USER }}
            script: whoami