name: Prod Deploy to Remote Server http://http://209.38.198.174//

permissions:
  pull-requests: read
  deployments: read
  contents: read

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  deploy_prod:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.1.0
      env:
        BRANCH: ${{ github.head_ref }}
        ENV: prod
      with:
            host: ${{ secrets.PROD_HOST }}
            key: ${{ secrets.PROD_SSH_KEY }}
            username: ${{ secrets.PROD_USERNAME }}
            script: |
                cd /home/${{ secrets.PROD_USERNAME }}/stuba-asos
                echo "Stopping and removing the containers"
                docker compose -f docker-compose-deploy.yaml down
                echo
                echo "Switching to main branch and pulling latest changes"
                git checkout main
                git pull origin main
                echo
                echo "PROD setup"
                echo "env: ${{env.ENV}}"
                echo "ENV=${{env.ENV}}" > .env
                echo "BACKEND_URL=${{ secrets.PROD_HOST }}" >> .env
                ls -l .env
                echp
                echo "Building and deploying the project"
                docker compose -f docker-compose-deploy.yaml up --build -d